# Generated by Django 3.2.5 on 2021-10-05 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='hi', upload_to='profiles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=30)),
                ('year_manufactured', models.DateTimeField()),
                ('image_1', models.ImageField(upload_to='cars')),
                ('image_2', models.ImageField(upload_to='cars')),
                ('image_3', models.ImageField(upload_to='cars')),
                ('image_4', models.ImageField(upload_to='cars')),
                ('car_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_app.location')),
            ],
        ),
    ]
