# Generated by Django 3.2.5 on 2021-10-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_app.user'),
            preserve_default=False,
        ),
    ]
