# Generated by Django 3.2.5 on 2021-10-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0003_car_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_location',
        ),
    ]
