# Generated by Django 3.2.5 on 2021-10-05 16:27

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='bomet', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_point',
            field=location_field.models.plain.PlainLocationField(default='locate', max_length=63),
            preserve_default=False,
        ),
    ]
